seed: 1234
lr: 1e-04
grad_accum: 4
grad_ckpt: True
gpu: 1
fp16: False
max_nodes: 150
num_features: 1
num_epochs: 100
batch_size: 512
every_n_epochs: 10
debug: False
early_stopping: True
remote: False
checkpointing: True
train: True
test: True


